### ISSUE TITLE
Path for the data files is incorrect in subcorpus.yaml

### ISSUE THREAD

**Issue by RaghavRoy145** [owainkenwayucl/coursework-c0235#1]
I didn't raise a PR because I'm not sure if I'm right.

For the bench-marking task: 

After running the gather.yaml, (and unzipping the files on the data-disk machines)

If I run subcorpus.yaml, it fails to find the zip files because the path to it is probably incorrect:
https://github.com/owainkenwayucl/coursework-c0235/blob/cbb353581177c284c34425a49ca936b4c4ef9329/lecture4a_dataengexample/subcorpus.yaml#L30

The source path should be `/home/almalinux/...`
Instead of the current `/data/almalinux/...`

It gets the benchmarks correctly after this change ("on my machine").

EDIT: This was probably because of my own misconfiguration

**Comment by owainkenwayucl** [comment]
HI,

Both /home/almalinux/data and /data/almalinux should point to the same place as the former should be a sym-link to the latter.

Cheers,
Owain
